### ISSUE TITLE
Can we do Hover over the data points?

### ISSUE THREAD

**Issue by Ibrokhimsadikov** [TutteInstitute/datamapplot#1]
It is great plot for data mapping of immense embeddings of texts with their corresponding cluster lable. It would be great if there is hover feature so that to see each data point

**Comment by lmcinnes** [comment]
Thanks. This particular library was explicitly designed for static plots. If you want interactivity then [ThisNotThat](https://github.com/TutteInstitute/thisnotthat) would be the place to head. It offers hover, but also rich summarization features and more as well.

**Comment by msat59** [comment]
Technically, it is possible to reproduce plots created by matplotlib in Plotly. I quickly looked at the code. The matplotlib and annotations part is not too hard, but I don't know yet what can be done to replace the datashader.

**Comment by lmcinnes** [comment]
I'm working on a custom solution using deck.gl that I think should meet these needs. Hopefully that can be made available in due course.

**Comment by Ibrokhimsadikov** [comment]
Hi @lmcinnes , is there any updates

**Comment by lmcinnes** [comment]
You can clone or check out the ``interactive`` branch if you want to play with what is in place now. There is a new function ``create_interactive_plot`` that you provide a filename to and it will create an html file with the interactive plot. It supports multiple layers of labelling (and different resolutions/granularities) and has some different options. It's not well documented yet, and remains experimental, so don't assume any functionality is fixed. I would welcome any feedback on what is in place so far though.

To give an idea of what is possible I have attached an example output for the ArXiv ML dataset. You'll need to download and unzip 
the html and open it locally: [arxiv_ml_datamap_layered_titles_only.zip](https://github.com/TutteInstitute/datamapplot/files/14152005/arxiv_ml_datamap_layered_titles_only.zip)

**Comment by Ibrokhimsadikov** [comment]
Thank you very much, example looks amazing, that is what I wanted to have, I want to render such plot into my streamlit app, so I think it is possible, I need to give it a try

**Comment by lmcinnes** [comment]
The branch is a little unstable at the moment as I have been pretty active changing things, so if it doesn't work, you can always try again in a few days and issues may magically resolve themselves. I expect to have documentation, examples, and a full release in the next couple of weeks, assuming all goes well.

**Comment by Ibrokhimsadikov** [comment]
Thank you for continuous support,

**Comment by Ibrokhimsadikov** [comment]
Is there a way if you could provide source data for the example arxiv plot, and also, would like to know if we could render plots in streamlit app as well, rather than only saving as a a html file, Thank you!

**Comment by lmcinnes** [comment]
I working to get some example prepared. The latest version of things returns an object with a ``_repr_html_`` method such that it renders natively inside notebooks. I've glanced briefly at streamlit docsumentation and it looks like it may support this? Otherwise calling ``str`` on the object will output the raw html which you can hopefully pass to a streamlit iframe or html class of some kind?

**Comment by lmcinnes** [comment]
I've gotten started on the docs, and conveniently the in-notebook visualizations render into the html docs very nicely, so it is possible to zoom and explore live in the docs. Work-in-progress [can be found here](https://datamapplot.readthedocs.io/en/interactive/interactive_intro.html); it should provide a working walkthrough of using the interactive plot on at least one example, and provide a quick idea of the scope of funtionality currently available (including the recently added on-click actions).

**Comment by lmcinnes** [comment]
It would be great if you can share anything you end up building with this, assuming that it works well enough for your needs.

**Comment by lmcinnes** [comment]
It is now in main; a release should be coming out soon.

**Comment by Ibrokhimsadikov** [comment]
@lmcinnes  thank you very much for your effort, I tested interactive datamapplot, I am impressed by how the plot is rendered. Amazing plot,
