### ISSUE TITLE
Code for producing layers

### ISSUE THREAD

**Issue by zilch42** [TutteInstitute/datamapplot#16]
Hi there, 

This is an excellent package, and I'm excited about the coming integration with BERTopic. I'm wondering if you have any example code for producing the different layers used in the interactive plot examples? Were they produced with BERTopic? 

Cheers

**Comment by lmcinnes** [comment]
I've actually been using my own custom code to do most of this for the examples. I've busy working on a clustering library designed to work with embeddings (text, image, etc.) that provides exactly this kind of layered clustering. Hopefully this will be easier once that is available. I have talked with Maarten about the layered clustering, so it is possible future versions of BERTopic may support it.

**Comment by zilch42** [comment]
Thanks Imcinnes, That sounds exciting. I look forward to checking that out!

**Comment by Ibrokhimsadikov** [comment]
Any, possibility to share the code, on how layered clusters are generated

**Comment by keyuchen21** [comment]
+ 1 ....... it will be very helpful if we can get some code ..... even messy will be super helpful!!!! :)
