### ISSUE TITLE
Failing rendering interactive plot in controlled environment!

### ISSUE THREAD

**Issue by Ibrokhimsadikov** [TutteInstitute/datamapplot#18]
Interactive plot is not rendering with the following error:

ConnectionError: ('Connection aborted.'  ConnectionResetError(104,  "Connection reset by peer")), may be my company firewall is restricting accesing google fonts api. Any way to debug it?

**Comment by lmcinnes** [comment]
Either using the dev tools in the browser, or open the actual html file
after saving it and edit out problematic calls one by one until you find
the culprit. Not ideal but should work.
