### ISSUE TITLE
Interactive plots no longer loading

### ISSUE THREAD

**Issue by Alethio-uk** [TutteInstitute/datamapplot#20]
Hi, 

It appears that interactive plots are no longer loading from html files. This includes any maps stored locally and the examples within the documentation on https://datamapplot.readthedocs.io/en/latest/interactive_intro.html 
The maps either fail to load all together, or get stuck on the spinning wheel. Static plots are unaffected. 

I'm also not currently able to create any new interactive plots. I'm assuming something is failing within the external calls when the maps load?

Screenshot below

<img width="1071" alt="Screenshot 2024-04-12 at 10 28 13" src="https://github.com/TutteInstitute/datamapplot/assets/60094749/c0f3e2f5-9701-43d3-bc0d-cfcfc6a25e45">

**Comment by lmcinnes** [comment]
They are loading here, so it is hard to debug what the issue is. I have heard some people having issues with google fonts, but that shouldn't really effect html files you've already created (it should just fallback on fonts).

**Comment by lmcinnes** [comment]
Okay, I've managed to have something fail to load. It seems like something has changed in the javascript ecosystem and loaders for deck.gl are no longer working. I honestly have no idea how to fix that right now, but I certainly understand that it is a major issue. I'll see what I can figure out ...

**Comment by Alethio-uk** [comment]
Appears to be working again for me too, thanks for looking into it

**Comment by lmcinnes** [comment]
Glad to hear things are back working. I guess this is the downside of relying on CDNs for javascript. Maybe in the future I'll try to have a version that can just inline all the javascript directly into the html?
