### ISSUE TITLE
Add ax parameter to create_plot function for subplot integration

### ISSUE THREAD

**Issue by huguesva** [TutteInstitute/datamapplot#40]
Hello, thanks for the great toolbox!

I have a recommendation (apologies if this is already possible):

It would be really useful if the `create_plot` function allowed an `ax` parameter to pass a `matplotlib` axis object. This would enable users to embed plots into existing figures and subplot grids without forcing the creation of a new figure. This feature would provide more flexibility when working with complex layouts, such as when using `matplotlib.subplots()`.

Thanks for considering this!

**Comment by lmcinnes** [comment]
That is a great suggestion. The current main branch on github has this, but I think the latest release on PyPI does not. I am working on a bunch of new features, so hopefully there will be another release in a month or so, and this will be available in a release then.
