### ISSUE TITLE
InteractiveFigure indefinitely renders as a spinner in Jupyter, exported HTML

### ISSUE THREAD

**Issue by akshayka** [TutteInstitute/datamapplot#43]
Kudos on the very cool package.

I am attempting the [Interactive DataMapPlots tutorial](https://datamapplot.readthedocs.io/en/latest/interactive_intro.html)  from the documentation in a Jupyter notebook. When I emit the plot as an output, I see a spinner rendering indefinitely:

![image](https://github.com/user-attachments/assets/99109929-b70b-401d-acb7-dd61a7532f16)

I exported the plot to HTML, and upon opening the HTML file in Chrome I see the same spinner.

In the browser console, I see the following error:

![image](https://github.com/user-attachments/assets/9f15e286-3190-4c7f-8fd8-ddddf177dc46)

Here are some of the packages in my environment and their versions:

```
datamapplot: 0.4.1
numpy: 2.0.0
ipython: 8.28.0
notebook: 7.2.2
```

The static plots do work just fine (and look beautiful).

As you can probably guess, I would ultimately love to have DataMapPlot work in [marimo notebooks](https://github.com/marimo-team/marimo), possibly with metadata about the selected points sent back to Python.

My apologies if this is simple user error.

**Comment by lmcinnes** [comment]
I don't think it is a user error, but I'll have to see if I can reproduce it.

I did have a plan to allow the output to be an Anywidget with selection indices being a value that get passed back. I don't know much about the details of getting Anywidget working, but my cursory reading through the tutorials made it seem like it was doable for at least a reasonable amount of the functionality. I'm assuming that Anywidget would make things work in Marimo?

The other alternative is that ultimately it is just rendering HTML into an iframe in jupyter (with some munging to work around some of jupyter's quirks. Is there something we could do for marimo that might work similarly?

**Comment by lmcinnes** [comment]
If the bounds computations happened to end up with np.float32 instead of python floats that would get rendered incorrectly into the HTML. Thanks for finding and reporting this, it's a bit of an embarrassing oversight on my part. Should be fixed now.

**Comment by akshayka** [comment]
No worries, thank you for the fix!

Yes, we marimo supports anywidget. We can try getting it working through that, and can upstream if we have good results.

**Comment by akshayka** [comment]
Can confirm that it now works: 

![image](https://github.com/user-attachments/assets/09011543-c6fc-4ac9-9083-d8043f4abc94)

Thanks for the quick fix.

**Comment by akshayka** [comment]
@lmcinnes , I'm seeing a similar issue but for plots with selection. Here is an example:

https://colab.research.google.com/drive/14Taj65FefFboB-7Ipi-RAZ1ADVeZWvpc?usp=sharing
